In [1]:
import pandas as pd

df= pd.read_csv("covid.csv",parse_dates=['Date'])

print("New Cases")
new_cases=int(input())
print("New Deaths")
new_deaths=int(input())
print("New Recoveries")
new_recoveries=int(input())


total_cases=df['Total Cases'].max()+new_cases
total_deaths=df['Total Deaths'].max()+new_deaths
total_recoveries=df['Total Recoveries'].max()+new_recoveries
new_date=df['Date'].max()+ pd.DateOffset(1)

new_df= pd.DataFrame({
        "Date": [new_date],
        "Total Cases": [total_cases],
        "New Cases": [new_cases],
        "Total Deaths": [total_deaths],
        "New Deaths": [new_deaths],
        "Total Recoveries": [total_recoveries],
        "New Recoveries": [new_recoveries]

})

final_df = pd.concat([df,new_df], ignore_index=True)
final_df.tail()

final_df.to_csv("covid.csv",index=False)
final_df.tail()

New Cases
341
New Deaths
10
New Recoveries
9

,Date,Total Cases,New Cases,Total Deaths,New Deaths,Total Recoveries,New Recoveries
35,2020-04-12,621,139,34,4,39,3
36,2020-04-13,803,182,39,5,42,3
37,2020-04-14,1012,209,46,7,42,0
38,2020-04-15,1231,219,50,4,49,7
39,2020-04-16,1572,341,60,10,58,9